#' @title
#'   Create a new Monty Hall Problem game.
#'
#' @description
#'   `create_game()` generates a new game that consists of two doors
#'   with goats behind them, and one with a car.
#'
#' @details
#'   The game setup replicates the game on the TV show "Let's
#'   Make a Deal" where there are three doors for a contestant
#'   to choose from, one of which has a car behind it and two
#'   have goats. The contestant selects a door, then the host
#'   opens a door to reveal a goat, and then the contestant is
#'   given an opportunity to stay with their original selection
#'   or switch to the other unopened door. There was a famous
#'   debate about whether it was optimal to stay or switch when
#'   given the option to switch, so this simulation was created
#'   to test both strategies.
#'
#' @param ... no arguments are used by the function.
#'
#' @return The function returns a length 3 character vector
#'   indicating the positions of goats and the car.
#'
#' @examples
#'   create_game()
#'
#' @export
create_game <- function() {
  a.game <- sample(x = c("goat", "goat", "car"), size = 3, replace = FALSE)
  return(a.game)
}

#' @title Select a Door
#'
#' @description This function randomly selects one of the three doors in the Monty Hall game.
#'
#' @details The function generates a random selection from the three available doors (labeled 1, 2, and 3) to simulate the contestant's choice.
#'
#' @param None. The function does not take any arguments.
#'
#' @return The function returns a single integer between 1 and 3, representing the contestant's selected door.
#'
#' @examples
#' select_door()
#'
#' @export
select_door <- function() {
  doors <- c(1, 2, 3)
  a.pick <- sample(doors, size = 1)
  return(a.pick)
}

#' @title Open a Goat Door
#'
#' @description This function simulates the host opening one of the doors with a goat behind it, after the contestant has made their initial choice.
#'
#' @details If the contestant has chosen the car, the function randomly selects one of the two remaining doors that hide a goat. If the contestant chooses a goat, the host opens the other door that hides a goat.
#'
#' @param game A character vector of length 3 generated by `create_game()`, representing the positions of the car and goats behind the doors.
#' @param a.pick An integer (1, 2, or 3) representing the contestant's selected door.
#'
#' @return The function returns an integer (1, 2, or 3) representing the door that the host opens to reveal a goat.
#'
#' @examples
#' game <- create_game()
#' a.pick <- select_door()
#' open_goat_door(game, a.pick)
#'
#' @export
open_goat_door <- function(game, a.pick) {
  doors <- c(1, 2, 3)
  if (game[a.pick] == "car") {
    goat.doors <- doors[game != "car"]
    opened.door <- sample(goat.doors, size = 1)
  }
  if (game[a.pick] == "goat") {
    opened.door <- doors[game != "car" & doors != a.pick]
  }
  return(opened.door)
}

#' @title Change Door Selection
#'
#' @description This function allows the contestant to either stay with their initial choice or switch to the other unopened door.
#'
#' @details If the contestant decides to stay, their final choice will be the same as their initial pick. If they switch, they will choose the other unopened door.
#'
#' @param stay A logical value. If `TRUE`, the contestant stays with their original choice. If `FALSE`, the contestant switches to the other unopened door.
#' @param opened.door An integer representing the door that the host has opened to reveal a goat.
#' @param a.pick An integer representing the contestant's initial door selection.
#'
#' @return The function returns an integer (1, 2, or 3) representing the contestant's final door choice.
#'
#' @examples
#' opened.door <- open_goat_door(game = create_game(), a.pick = select_door())
#' change_door(stay = TRUE, opened.door, a.pick = 1)
#'
#' @export
change_door <- function(stay = TRUE, opened.door, a.pick) {
  doors <- c(1, 2, 3)
  if (stay) {
    final.pick <- a.pick
  } else {
    final.pick <- doors[doors != opened.door & doors != a.pick]
  }
  return(final.pick)
}

#' @title Determine Game Outcome
#'
#' @description This function determines whether the contestant has won or lost the game based on their final door selection.
#'
#' @details If the contestant's final choice is the door with the car behind it, they win. If their final choice is a door with a goat behind it, they lose.
#'
#' @param final.pick An integer representing the contestant's final door choice.
#' @param game A character vector generated by `create_game()`, representing the positions of the car and goats behind the doors.
#'
#' @return The function returns a string: "WIN" if the contestant chose the car, or "LOSE" if they chose a goat.
#'
#' @examples
#' game <- create_game()
#' final.pick <- change_door(stay = TRUE, opened.door = open_goat_door(game, a.pick = select_door()), a.pick = 1)
#' determine_winner(final.pick, game)
#'
#' @export
determine_winner <- function(final.pick, game) {
  if (game[final.pick] == "car") {
    return("WIN")
  } else {
    return("LOSE")
  }
}

#' @title Simulate a Single Monty Hall Game
#'
#' @description This function simulates a single instance of the Monty Hall game, testing both strategies: staying with the initial choice and switching.
#'
#' @details The function runs through the entire Monty Hall game process, from selecting a door, opening a goat door, to determining whether staying or switching results in a win or loss.
#'
#' @return The function returns a data frame with two rows: one for the "stay" strategy and one for the "switch" strategy. The outcome of each strategy is recorded as either "WIN" or "LOSE".
#'
#' @examples
#' play_game()
#'
#' @export
play_game <- function() {
  new.game <- create_game()
  first.pick <- select_door()
  opened.door <- open_goat_door(new.game, first.pick)

  final.pick.stay <- change_door(stay = TRUE, opened.door, first.pick)
  final.pick.switch <- change_door(stay = FALSE, opened.door, first.pick)

  outcome.stay <- determine_winner(final.pick.stay, new.game)
  outcome.switch <- determine_winner(final.pick.switch, new.game)

  strategy <- c("stay", "switch")
  outcome <- c(outcome.stay, outcome.switch)
  game.results <- data.frame(strategy, outcome, stringsAsFactors = FALSE)
  return(game.results)
}

#' @title Simulate Multiple Monty Hall Games
#'
#' @description This function simulates `n` games of the Monty Hall problem and summarizes the results for both strategies (stay and switch).
#'
#' @details The function simulates the Monty Hall game multiple times and reports the win/loss proportions for each strategy.
#'
#' @param n The number of games to simulate. Default is 100.
#'
#' @return The function returns a data frame containing the outcome for each game and prints a summary table of the win proportions for the stay and switch strategies.
#'
#' @examples
#' play_n_games(100)
#'
#' @export
play_n_games <- function(n = 100) {
  library(dplyr)
  results.list <- list()  # collector
  loop.count <- 1

  for (i in 1:n) {  # iterator
    game.outcome <- play_game()
    results.list[[loop.count]] <- game.outcome
    loop.count <- loop.count + 1
  }

  results.df <- dplyr::bind_rows(results.list)

  table(results.df) %>%
    prop.table(margin = 1) %>%
    round(2) %>%
    print()

  return(results.df)
}
